CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

CREATE TABLE shortened_urls (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    url text NOT NULL,
    key character varying(20) NOT NULL,
    CONSTRAINT pk_shortened_urls PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_shortened_urls_key ON shortened_urls (key);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20210113094032_Initial', '5.0.2');

COMMIT;